// Code generated by MockGen. DO NOT EDIT.
// Source: unit-test/internal/awsiface (interfaces: S3PutObject)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	s3 "github.com/aws/aws-sdk-go-v2/service/s3"
	gomock "github.com/golang/mock/gomock"
)

// MockS3PutObject is a mock of S3PutObject interface.
type MockS3PutObject struct {
	ctrl     *gomock.Controller
	recorder *MockS3PutObjectMockRecorder
}

// MockS3PutObjectMockRecorder is the mock recorder for MockS3PutObject.
type MockS3PutObjectMockRecorder struct {
	mock *MockS3PutObject
}

// NewMockS3PutObject creates a new mock instance.
func NewMockS3PutObject(ctrl *gomock.Controller) *MockS3PutObject {
	mock := &MockS3PutObject{ctrl: ctrl}
	mock.recorder = &MockS3PutObjectMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3PutObject) EXPECT() *MockS3PutObjectMockRecorder {
	return m.recorder
}

// GetObject mocks base method.
func (m *MockS3PutObject) GetObject(arg0 context.Context, arg1 *s3.GetObjectInput, arg2 ...func(*s3.Options)) (*s3.GetObjectOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetObject", varargs...)
	ret0, _ := ret[0].(*s3.GetObjectOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *MockS3PutObjectMockRecorder) GetObject(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockS3PutObject)(nil).GetObject), varargs...)
}

// PutObject mocks base method.
func (m *MockS3PutObject) PutObject(arg0 context.Context, arg1 *s3.PutObjectInput, arg2 ...func(*s3.Options)) (*s3.PutObjectOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutObject", varargs...)
	ret0, _ := ret[0].(*s3.PutObjectOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutObject indicates an expected call of PutObject.
func (mr *MockS3PutObjectMockRecorder) PutObject(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject", reflect.TypeOf((*MockS3PutObject)(nil).PutObject), varargs...)
}
