AWSTemplateFormatVersion: '2010-09-09'
Description: 'LogGuardian - Lambda Function for Log Group Compliance Remediation'

Parameters:
  DeploymentBucket:
    Type: String
    Description: S3 bucket containing Lambda deployment package
    
  LambdaCodeKey:
    Type: String
    Default: logguardian-compliance.zip
    Description: S3 key for Lambda deployment package
    
  LambdaMemorySize:
    Type: Number
    Default: 256
    MinValue: 128
    MaxValue: 3008
    Description: Memory allocation for Lambda function (MB)
    
  LambdaTimeout:
    Type: Number
    Default: 900
    MinValue: 1
    MaxValue: 900
    Description: Lambda function timeout in seconds
    
  LambdaExecutionRoleArn:
    Type: String
    Description: ARN of the Lambda execution role
    
  KMSKeyAlias:
    Type: String
    Default: alias/logguardian-logs
    Description: KMS key alias for log group encryption
    
  KMSKeyArn:
    Type: String
    Default: ""
    Description: ARN of KMS key for log group encryption (optional)
    
  DefaultRetentionDays:
    Type: Number
    Default: 365
    Description: Default retention period for log groups in days
    
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Deployment environment



Conditions:
  HasKMSKey: !Not [!Equals [!Ref KMSKeyArn, ""]]

Resources:
  # Lambda Function
  LogGuardianLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "logguardian-${Environment}"
      Description: "LogGuardian - Automated CloudWatch log group compliance remediation"
      Runtime: provided.al2023
      Handler: main
      Code:
        S3Bucket: !Ref DeploymentBucket
        S3Key: !Ref LambdaCodeKey
      Role: !Ref LambdaExecutionRoleArn
      MemorySize: !Ref LambdaMemorySize
      Timeout: !Ref LambdaTimeout
      Environment:
        Variables:
          KMS_KEY_ALIAS: !Ref KMSKeyAlias
          KMS_KEY_ARN: !If
            - HasKMSKey
            - !Ref KMSKeyArn
            - ""
          DEFAULT_RETENTION_DAYS: !Ref DefaultRetentionDays
          ENVIRONMENT: !Ref Environment
          LOG_LEVEL: INFO
      ReservedConcurrencyLimit: 5
      DeadLetterConfig:
        TargetArn: !GetAtt LogGuardianDLQ.Arn
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: LogGuardian

  # CloudWatch Log Group for Lambda Logs
  LogGuardianLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/logguardian-${Environment}"
      RetentionInDays: 30
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: LogGuardian

  # Dead Letter Queue for failed executions
  LogGuardianDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "logguardian-dlq-${Environment}"
      MessageRetentionPeriod: 1209600  # 14 days
      VisibilityTimeoutSeconds: 60
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: LogGuardian

  # Lambda Version (for alias management)
  LogGuardianLambdaVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref LogGuardianLambda
      Description: !Sub "Version deployed on ${Environment}"

  # Lambda Alias for environment-specific deployment
  LogGuardianLambdaAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref LogGuardianLambda
      FunctionVersion: !GetAtt LogGuardianLambdaVersion.Version
      Name: !Ref Environment
      Description: !Sub "Alias for ${Environment} environment"

Outputs:
  LambdaFunctionArn:
    Description: ARN of the LogGuardian Lambda function
    Value: !GetAtt LogGuardianLambda.Arn
    Export:
      Name: !Sub "${AWS::StackName}-LambdaFunctionArn"
      
  LambdaFunctionName:
    Description: Name of the LogGuardian Lambda function
    Value: !Ref LogGuardianLambda
    Export:
      Name: !Sub "${AWS::StackName}-LambdaFunctionName"
      
  LambdaAliasArn:
    Description: ARN of the Lambda alias
    Value: !Ref LogGuardianLambdaAlias
    Export:
      Name: !Sub "${AWS::StackName}-LambdaAliasArn"
      
  DeadLetterQueueArn:
    Description: ARN of the dead letter queue
    Value: !GetAtt LogGuardianDLQ.Arn
    Export:
      Name: !Sub "${AWS::StackName}-DeadLetterQueueArn"
